# Generated by Django 3.0.14 on 2021-05-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='Research_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Research_title',
        ),
        migrations.AddField(
            model_name='post',
            name='mail',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
